### ISSUE TITLE
[Feature] TODO code comment finder

### ISSUE THREAD

**Issue by v3rse** [v3rse/done#4]
# Problem

Whenever you put in `//TODO <message>` you may want to add these messages to your list of **done**  task.

Even better you can attach these tasks to a commit as described in #3 
# Some enhancements
- [x] Find all comments with label `TODO` in a file.
- [x] Add them to your list of Pending todos.  
- [ ] Find all comments with label `TODO` in your current code directory and subdirectories.

**Comment by v3rse** [comment]
With PR #5  you can do `done triage <file>` and it will add all TODO tagged comments to  your pending list.

NB: It uses `/[\/\/|\#]\s*?TODO/i` when trying to find them.

@oddoye-david Now what I'm trying to figure out is whether `triage` subdirectories recursively is good idea. 

Let me know what you think of the feature so far

**Comment by oddoye-david** [comment]
@v3rse Maybe we could add a flag to indicate which directory/file to `triage`. ie `done triage -f <file>` and `done triage -d /src/**/*.js`

**Comment by v3rse** [comment]
@oddoye-david That's a good idea. But by using `fs.lstatSync()` we can check for where the path passed is directory or file using `fs.Stats.isDirectory()`and `fs.Stats.isFile()`  eliminating the need for a flag.

What I meant is that should we search directories passed recursively for `TODO` tags or should we just stick with doing files.

Thinking of this on a usability and UX level.
